### ISSUE TITLE
Solution: Content to code

### ISSUE THREAD

**Issue by Rachel-Norman** [Rachel-Norman/content-to-code#1]
@wendywarren

1. main — primary content of the page
2. h1 — heading 1, the most important content 
3. time datetime="" — marks text as a date or time 
4. p — paragraph of text
5. video — embedded video
6. h2 — sub-heading of h1
7. p — paragraph of text
8. strong — highly emphasized text 
9. data — numerical piece of information 
10. time datetime="" — marks text as a date or time
11. a — link to another website 
12. h2 — sub-heading of h1
13. ol — ordered list
14. li — a list item 
15. h2 — sub-heading of h1
16. dl — description list 
17. dt — description title/term 
18. dd — description definition 
19. h2 — sub-heading of h1
20. blockquote — stand alone quote 
21. p — paragraph of text
22. 
23. cite — citation for another source 
24. h2 — sub-heading of h1
25. address — address

**Comment by wendywarren** [comment]
Great job @Rachel-Norman!!

The only correction I have to make is #13 but almost everyone incorrectly answered that. I clarified in class but here is an explanation I sent everyone.

The list is `<ul>` but the list is in alphabetical order so I do see why you decided that but `<ol>` items display with a preceding marker of either a number or letter. Example: 1.,2.,3., or a., b., c., etc...

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ol

Let me know if you have any questions.

Wendy
